### ISSUE TITLE
Update access token in `.travis.yml`

### ISSUE THREAD

**Issue by floscher** [fieldpapers/josm-fieldpapers#11]
Currently Travis CI can't publish releases for this repository, because it still has the token for the old repository location `iandeed/josm-fieldpapers`:

https://github.com/fieldpapers/josm-fieldpapers/blob/d832503980c9cf914e4cac20fc5dea6e7c2ba1c8/.travis.yml#L8-L10

**Comment by iandees** [comment]
Ah, thanks for checking into that, @floscher!

**Comment by floscher** [comment]
Fixed in 04698ac7b45b721bd3344c2a6e9fe66b90348359.
