### ISSUE TITLE
plugin version is not available

### ISSUE THREAD

**Issue by silpol** [fieldpapers/josm-fieldpapers#2]
when I start JOSM from command line, I see this message (among others)

WARNING: Missing plugin main version in plugin fieldpapers

**Comment by floscher** [comment]
This should now be fixed, as the plugin now defines a `Plugin-Mainversion` in the manifest.

**Comment by floscher** [comment]
This should now be fixed, as the plugin now defines a `Plugin-Mainversion` in the manifest.

**Comment by quincylvania** [comment]
Trusing @floscher that this is fixed.
