### ISSUE TITLE
pasting fieldpapers id using mouse click

### ISSUE THREAD

**Issue by emirhartato** [fieldpapers/josm-fieldpapers#3]
# Problems

There are people that not getting used to keyboard shortcut for pasting. So it will be good if people also can use right-click mouse - paste to do it.

**Comment by uryevich** [comment]
I use Mac and josm. When I start using The Field Papers plugin, I was unhappy that I can't paste FP snapshot url in input window. I try with Cmd+V (similar to windows Ctrl+V), try use mouse context menu, but nothing works. If I enter url manually (sic). Please add paste options to input field!

**Comment by maning** [comment]
@uryevich, yes this is confusing, but in JOSM, paste is still `Ctrl-V`.

**Comment by uryevich** [comment]
@maning Thanks!

**Comment by floscher** [comment]
This is fixed now that #6 is merged. See ff123291cba89e22ab6a3ea56cbe40e7496afc6c.
